### ISSUE TITLE
Add plugin to Flask Extensions page

### ISSUE THREAD

**Issue by iurisilvio** [mikeboers/Flask-Images#11]
- [x] An approved Flask extension requires a maintainer. In the event an extension author would like to move beyond the project, the project should find a new maintainer including full source hosting transition and PyPI access. If no maintainer is available, give access to the Flask core team.
- [x] An approved Flask extension must provide exactly one package or module named flask_extensionname. They might also reside inside a flaskext namespace packages though this is discouraged now.
- [x] It must ship a testing suite that can either be invoked with make test or python setup.py test. For test suites invoked with make test the extension has to ensure that all dependencies for the test are installed automatically. If tests are invoked with python setup.py test, test dependencies can be specified in the setup.py file. The test suite also has to be part of the distribution.
- [x] APIs of approved extensions will be checked for the following characteristics:
  an approved extension has to support multiple applications running in the same Python process.
  it must be possible to use the factory pattern for creating applications.
- [x] The license must be BSD/MIT/WTFPL licensed.
- [x] The naming scheme for official extensions is Flask-ExtensionName or ExtensionName-Flask.
- [x] Approved extensions must define all their dependencies in the setup.py file unless a dependency cannot be met because it is not available on PyPI.
- [ ] The extension must have documentation that uses one of the two Flask themes for Sphinx documentation.
- [x] The zip_safe flag in the setup script must be set to False, even if the extension would be safe for zipping.
- [x] An extension currently has to support Python 2.6 as well as Python 2.7

**Comment by mikeboers** [comment]
At some point in recent history I translated the existing docs from Markdown to Sphinx. They are still kinda gross, but there they are.

What do you think?
